global:
  virtualGarden:
    enabled: false
  image:
    repository: eu.gcr.io/gardener-project/gardener/extensions/admission-kubevirt
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 1
  resources: {}
  webhookConfig:
    caBundle: |
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
    serverPort: 10250
    tls:
      crt: |
        -----BEGIN CERTIFICATE-----
        ...
        -----END CERTIFICATE-----
      key: |
        -----BEGIN RSA PRIVATE KEY-----
        ...
        -----END RSA PRIVATE KEY-----
    # Please make sure you are running `gardener@v1.42` or later before setting this to true.
    useObjectSelector: false
  # Kubeconfig to the target cluster. In-cluster configuration will be used if not specified.
  kubeconfig:
