// +build !ignore_autogenerated

/*
Copyright (c) 2020 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	kubevirt "github.com/gardener/gardener-extension-provider-kubevirt/pkg/apis/kubevirt"
	v1 "k8s.io/api/core/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*CloudControllerManagerConfig)(nil), (*kubevirt.CloudControllerManagerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CloudControllerManagerConfig_To_kubevirt_CloudControllerManagerConfig(a.(*CloudControllerManagerConfig), b.(*kubevirt.CloudControllerManagerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubevirt.CloudControllerManagerConfig)(nil), (*CloudControllerManagerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubevirt_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig(a.(*kubevirt.CloudControllerManagerConfig), b.(*CloudControllerManagerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*CloudProfileConfig)(nil), (*kubevirt.CloudProfileConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_CloudProfileConfig_To_kubevirt_CloudProfileConfig(a.(*CloudProfileConfig), b.(*kubevirt.CloudProfileConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubevirt.CloudProfileConfig)(nil), (*CloudProfileConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubevirt_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(a.(*kubevirt.CloudProfileConfig), b.(*CloudProfileConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ControlPlaneConfig)(nil), (*kubevirt.ControlPlaneConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ControlPlaneConfig_To_kubevirt_ControlPlaneConfig(a.(*ControlPlaneConfig), b.(*kubevirt.ControlPlaneConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubevirt.ControlPlaneConfig)(nil), (*ControlPlaneConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubevirt_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(a.(*kubevirt.ControlPlaneConfig), b.(*ControlPlaneConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InfrastructureConfig)(nil), (*kubevirt.InfrastructureConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InfrastructureConfig_To_kubevirt_InfrastructureConfig(a.(*InfrastructureConfig), b.(*kubevirt.InfrastructureConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubevirt.InfrastructureConfig)(nil), (*InfrastructureConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubevirt_InfrastructureConfig_To_v1alpha1_InfrastructureConfig(a.(*kubevirt.InfrastructureConfig), b.(*InfrastructureConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*InfrastructureStatus)(nil), (*kubevirt.InfrastructureStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_InfrastructureStatus_To_kubevirt_InfrastructureStatus(a.(*InfrastructureStatus), b.(*kubevirt.InfrastructureStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubevirt.InfrastructureStatus)(nil), (*InfrastructureStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubevirt_InfrastructureStatus_To_v1alpha1_InfrastructureStatus(a.(*kubevirt.InfrastructureStatus), b.(*InfrastructureStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineImage)(nil), (*kubevirt.MachineImage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineImage_To_kubevirt_MachineImage(a.(*MachineImage), b.(*kubevirt.MachineImage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubevirt.MachineImage)(nil), (*MachineImage)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubevirt_MachineImage_To_v1alpha1_MachineImage(a.(*kubevirt.MachineImage), b.(*MachineImage), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineImageVersion)(nil), (*kubevirt.MachineImageVersion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineImageVersion_To_kubevirt_MachineImageVersion(a.(*MachineImageVersion), b.(*kubevirt.MachineImageVersion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubevirt.MachineImageVersion)(nil), (*MachineImageVersion)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubevirt_MachineImageVersion_To_v1alpha1_MachineImageVersion(a.(*kubevirt.MachineImageVersion), b.(*MachineImageVersion), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*MachineImages)(nil), (*kubevirt.MachineImages)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_MachineImages_To_kubevirt_MachineImages(a.(*MachineImages), b.(*kubevirt.MachineImages), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubevirt.MachineImages)(nil), (*MachineImages)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubevirt_MachineImages_To_v1alpha1_MachineImages(a.(*kubevirt.MachineImages), b.(*MachineImages), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkAttachmentDefinitionReference)(nil), (*kubevirt.NetworkAttachmentDefinitionReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NetworkAttachmentDefinitionReference_To_kubevirt_NetworkAttachmentDefinitionReference(a.(*NetworkAttachmentDefinitionReference), b.(*kubevirt.NetworkAttachmentDefinitionReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubevirt.NetworkAttachmentDefinitionReference)(nil), (*NetworkAttachmentDefinitionReference)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubevirt_NetworkAttachmentDefinitionReference_To_v1alpha1_NetworkAttachmentDefinitionReference(a.(*kubevirt.NetworkAttachmentDefinitionReference), b.(*NetworkAttachmentDefinitionReference), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkStatus)(nil), (*kubevirt.NetworkStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NetworkStatus_To_kubevirt_NetworkStatus(a.(*NetworkStatus), b.(*kubevirt.NetworkStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubevirt.NetworkStatus)(nil), (*NetworkStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubevirt_NetworkStatus_To_v1alpha1_NetworkStatus(a.(*kubevirt.NetworkStatus), b.(*NetworkStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworksConfig)(nil), (*kubevirt.NetworksConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NetworksConfig_To_kubevirt_NetworksConfig(a.(*NetworksConfig), b.(*kubevirt.NetworksConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubevirt.NetworksConfig)(nil), (*NetworksConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubevirt_NetworksConfig_To_v1alpha1_NetworksConfig(a.(*kubevirt.NetworksConfig), b.(*NetworksConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*TenantNetwork)(nil), (*kubevirt.TenantNetwork)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_TenantNetwork_To_kubevirt_TenantNetwork(a.(*TenantNetwork), b.(*kubevirt.TenantNetwork), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubevirt.TenantNetwork)(nil), (*TenantNetwork)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubevirt_TenantNetwork_To_v1alpha1_TenantNetwork(a.(*kubevirt.TenantNetwork), b.(*TenantNetwork), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WorkerConfig)(nil), (*kubevirt.WorkerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_WorkerConfig_To_kubevirt_WorkerConfig(a.(*WorkerConfig), b.(*kubevirt.WorkerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubevirt.WorkerConfig)(nil), (*WorkerConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubevirt_WorkerConfig_To_v1alpha1_WorkerConfig(a.(*kubevirt.WorkerConfig), b.(*WorkerConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*WorkerStatus)(nil), (*kubevirt.WorkerStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_WorkerStatus_To_kubevirt_WorkerStatus(a.(*WorkerStatus), b.(*kubevirt.WorkerStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubevirt.WorkerStatus)(nil), (*WorkerStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubevirt_WorkerStatus_To_v1alpha1_WorkerStatus(a.(*kubevirt.WorkerStatus), b.(*WorkerStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_CloudControllerManagerConfig_To_kubevirt_CloudControllerManagerConfig(in *CloudControllerManagerConfig, out *kubevirt.CloudControllerManagerConfig, s conversion.Scope) error {
	out.FeatureGates = *(*map[string]bool)(unsafe.Pointer(&in.FeatureGates))
	return nil
}

// Convert_v1alpha1_CloudControllerManagerConfig_To_kubevirt_CloudControllerManagerConfig is an autogenerated conversion function.
func Convert_v1alpha1_CloudControllerManagerConfig_To_kubevirt_CloudControllerManagerConfig(in *CloudControllerManagerConfig, out *kubevirt.CloudControllerManagerConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_CloudControllerManagerConfig_To_kubevirt_CloudControllerManagerConfig(in, out, s)
}

func autoConvert_kubevirt_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig(in *kubevirt.CloudControllerManagerConfig, out *CloudControllerManagerConfig, s conversion.Scope) error {
	out.FeatureGates = *(*map[string]bool)(unsafe.Pointer(&in.FeatureGates))
	return nil
}

// Convert_kubevirt_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig is an autogenerated conversion function.
func Convert_kubevirt_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig(in *kubevirt.CloudControllerManagerConfig, out *CloudControllerManagerConfig, s conversion.Scope) error {
	return autoConvert_kubevirt_CloudControllerManagerConfig_To_v1alpha1_CloudControllerManagerConfig(in, out, s)
}

func autoConvert_v1alpha1_CloudProfileConfig_To_kubevirt_CloudProfileConfig(in *CloudProfileConfig, out *kubevirt.CloudProfileConfig, s conversion.Scope) error {
	out.MachineImages = *(*[]kubevirt.MachineImages)(unsafe.Pointer(&in.MachineImages))
	return nil
}

// Convert_v1alpha1_CloudProfileConfig_To_kubevirt_CloudProfileConfig is an autogenerated conversion function.
func Convert_v1alpha1_CloudProfileConfig_To_kubevirt_CloudProfileConfig(in *CloudProfileConfig, out *kubevirt.CloudProfileConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_CloudProfileConfig_To_kubevirt_CloudProfileConfig(in, out, s)
}

func autoConvert_kubevirt_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(in *kubevirt.CloudProfileConfig, out *CloudProfileConfig, s conversion.Scope) error {
	out.MachineImages = *(*[]MachineImages)(unsafe.Pointer(&in.MachineImages))
	return nil
}

// Convert_kubevirt_CloudProfileConfig_To_v1alpha1_CloudProfileConfig is an autogenerated conversion function.
func Convert_kubevirt_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(in *kubevirt.CloudProfileConfig, out *CloudProfileConfig, s conversion.Scope) error {
	return autoConvert_kubevirt_CloudProfileConfig_To_v1alpha1_CloudProfileConfig(in, out, s)
}

func autoConvert_v1alpha1_ControlPlaneConfig_To_kubevirt_ControlPlaneConfig(in *ControlPlaneConfig, out *kubevirt.ControlPlaneConfig, s conversion.Scope) error {
	out.CloudControllerManager = (*kubevirt.CloudControllerManagerConfig)(unsafe.Pointer(in.CloudControllerManager))
	return nil
}

// Convert_v1alpha1_ControlPlaneConfig_To_kubevirt_ControlPlaneConfig is an autogenerated conversion function.
func Convert_v1alpha1_ControlPlaneConfig_To_kubevirt_ControlPlaneConfig(in *ControlPlaneConfig, out *kubevirt.ControlPlaneConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_ControlPlaneConfig_To_kubevirt_ControlPlaneConfig(in, out, s)
}

func autoConvert_kubevirt_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(in *kubevirt.ControlPlaneConfig, out *ControlPlaneConfig, s conversion.Scope) error {
	out.CloudControllerManager = (*CloudControllerManagerConfig)(unsafe.Pointer(in.CloudControllerManager))
	return nil
}

// Convert_kubevirt_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig is an autogenerated conversion function.
func Convert_kubevirt_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(in *kubevirt.ControlPlaneConfig, out *ControlPlaneConfig, s conversion.Scope) error {
	return autoConvert_kubevirt_ControlPlaneConfig_To_v1alpha1_ControlPlaneConfig(in, out, s)
}

func autoConvert_v1alpha1_InfrastructureConfig_To_kubevirt_InfrastructureConfig(in *InfrastructureConfig, out *kubevirt.InfrastructureConfig, s conversion.Scope) error {
	if err := Convert_v1alpha1_NetworksConfig_To_kubevirt_NetworksConfig(&in.Networks, &out.Networks, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_InfrastructureConfig_To_kubevirt_InfrastructureConfig is an autogenerated conversion function.
func Convert_v1alpha1_InfrastructureConfig_To_kubevirt_InfrastructureConfig(in *InfrastructureConfig, out *kubevirt.InfrastructureConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_InfrastructureConfig_To_kubevirt_InfrastructureConfig(in, out, s)
}

func autoConvert_kubevirt_InfrastructureConfig_To_v1alpha1_InfrastructureConfig(in *kubevirt.InfrastructureConfig, out *InfrastructureConfig, s conversion.Scope) error {
	if err := Convert_kubevirt_NetworksConfig_To_v1alpha1_NetworksConfig(&in.Networks, &out.Networks, s); err != nil {
		return err
	}
	return nil
}

// Convert_kubevirt_InfrastructureConfig_To_v1alpha1_InfrastructureConfig is an autogenerated conversion function.
func Convert_kubevirt_InfrastructureConfig_To_v1alpha1_InfrastructureConfig(in *kubevirt.InfrastructureConfig, out *InfrastructureConfig, s conversion.Scope) error {
	return autoConvert_kubevirt_InfrastructureConfig_To_v1alpha1_InfrastructureConfig(in, out, s)
}

func autoConvert_v1alpha1_InfrastructureStatus_To_kubevirt_InfrastructureStatus(in *InfrastructureStatus, out *kubevirt.InfrastructureStatus, s conversion.Scope) error {
	out.Networks = *(*[]kubevirt.NetworkStatus)(unsafe.Pointer(&in.Networks))
	return nil
}

// Convert_v1alpha1_InfrastructureStatus_To_kubevirt_InfrastructureStatus is an autogenerated conversion function.
func Convert_v1alpha1_InfrastructureStatus_To_kubevirt_InfrastructureStatus(in *InfrastructureStatus, out *kubevirt.InfrastructureStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_InfrastructureStatus_To_kubevirt_InfrastructureStatus(in, out, s)
}

func autoConvert_kubevirt_InfrastructureStatus_To_v1alpha1_InfrastructureStatus(in *kubevirt.InfrastructureStatus, out *InfrastructureStatus, s conversion.Scope) error {
	out.Networks = *(*[]NetworkStatus)(unsafe.Pointer(&in.Networks))
	return nil
}

// Convert_kubevirt_InfrastructureStatus_To_v1alpha1_InfrastructureStatus is an autogenerated conversion function.
func Convert_kubevirt_InfrastructureStatus_To_v1alpha1_InfrastructureStatus(in *kubevirt.InfrastructureStatus, out *InfrastructureStatus, s conversion.Scope) error {
	return autoConvert_kubevirt_InfrastructureStatus_To_v1alpha1_InfrastructureStatus(in, out, s)
}

func autoConvert_v1alpha1_MachineImage_To_kubevirt_MachineImage(in *MachineImage, out *kubevirt.MachineImage, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	out.SourceURL = in.SourceURL
	return nil
}

// Convert_v1alpha1_MachineImage_To_kubevirt_MachineImage is an autogenerated conversion function.
func Convert_v1alpha1_MachineImage_To_kubevirt_MachineImage(in *MachineImage, out *kubevirt.MachineImage, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineImage_To_kubevirt_MachineImage(in, out, s)
}

func autoConvert_kubevirt_MachineImage_To_v1alpha1_MachineImage(in *kubevirt.MachineImage, out *MachineImage, s conversion.Scope) error {
	out.Name = in.Name
	out.Version = in.Version
	out.SourceURL = in.SourceURL
	return nil
}

// Convert_kubevirt_MachineImage_To_v1alpha1_MachineImage is an autogenerated conversion function.
func Convert_kubevirt_MachineImage_To_v1alpha1_MachineImage(in *kubevirt.MachineImage, out *MachineImage, s conversion.Scope) error {
	return autoConvert_kubevirt_MachineImage_To_v1alpha1_MachineImage(in, out, s)
}

func autoConvert_v1alpha1_MachineImageVersion_To_kubevirt_MachineImageVersion(in *MachineImageVersion, out *kubevirt.MachineImageVersion, s conversion.Scope) error {
	out.Version = in.Version
	out.SourceURL = in.SourceURL
	return nil
}

// Convert_v1alpha1_MachineImageVersion_To_kubevirt_MachineImageVersion is an autogenerated conversion function.
func Convert_v1alpha1_MachineImageVersion_To_kubevirt_MachineImageVersion(in *MachineImageVersion, out *kubevirt.MachineImageVersion, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineImageVersion_To_kubevirt_MachineImageVersion(in, out, s)
}

func autoConvert_kubevirt_MachineImageVersion_To_v1alpha1_MachineImageVersion(in *kubevirt.MachineImageVersion, out *MachineImageVersion, s conversion.Scope) error {
	out.Version = in.Version
	out.SourceURL = in.SourceURL
	return nil
}

// Convert_kubevirt_MachineImageVersion_To_v1alpha1_MachineImageVersion is an autogenerated conversion function.
func Convert_kubevirt_MachineImageVersion_To_v1alpha1_MachineImageVersion(in *kubevirt.MachineImageVersion, out *MachineImageVersion, s conversion.Scope) error {
	return autoConvert_kubevirt_MachineImageVersion_To_v1alpha1_MachineImageVersion(in, out, s)
}

func autoConvert_v1alpha1_MachineImages_To_kubevirt_MachineImages(in *MachineImages, out *kubevirt.MachineImages, s conversion.Scope) error {
	out.Name = in.Name
	out.Versions = *(*[]kubevirt.MachineImageVersion)(unsafe.Pointer(&in.Versions))
	return nil
}

// Convert_v1alpha1_MachineImages_To_kubevirt_MachineImages is an autogenerated conversion function.
func Convert_v1alpha1_MachineImages_To_kubevirt_MachineImages(in *MachineImages, out *kubevirt.MachineImages, s conversion.Scope) error {
	return autoConvert_v1alpha1_MachineImages_To_kubevirt_MachineImages(in, out, s)
}

func autoConvert_kubevirt_MachineImages_To_v1alpha1_MachineImages(in *kubevirt.MachineImages, out *MachineImages, s conversion.Scope) error {
	out.Name = in.Name
	out.Versions = *(*[]MachineImageVersion)(unsafe.Pointer(&in.Versions))
	return nil
}

// Convert_kubevirt_MachineImages_To_v1alpha1_MachineImages is an autogenerated conversion function.
func Convert_kubevirt_MachineImages_To_v1alpha1_MachineImages(in *kubevirt.MachineImages, out *MachineImages, s conversion.Scope) error {
	return autoConvert_kubevirt_MachineImages_To_v1alpha1_MachineImages(in, out, s)
}

func autoConvert_v1alpha1_NetworkAttachmentDefinitionReference_To_kubevirt_NetworkAttachmentDefinitionReference(in *NetworkAttachmentDefinitionReference, out *kubevirt.NetworkAttachmentDefinitionReference, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespace = in.Namespace
	return nil
}

// Convert_v1alpha1_NetworkAttachmentDefinitionReference_To_kubevirt_NetworkAttachmentDefinitionReference is an autogenerated conversion function.
func Convert_v1alpha1_NetworkAttachmentDefinitionReference_To_kubevirt_NetworkAttachmentDefinitionReference(in *NetworkAttachmentDefinitionReference, out *kubevirt.NetworkAttachmentDefinitionReference, s conversion.Scope) error {
	return autoConvert_v1alpha1_NetworkAttachmentDefinitionReference_To_kubevirt_NetworkAttachmentDefinitionReference(in, out, s)
}

func autoConvert_kubevirt_NetworkAttachmentDefinitionReference_To_v1alpha1_NetworkAttachmentDefinitionReference(in *kubevirt.NetworkAttachmentDefinitionReference, out *NetworkAttachmentDefinitionReference, s conversion.Scope) error {
	out.Name = in.Name
	out.Namespace = in.Namespace
	return nil
}

// Convert_kubevirt_NetworkAttachmentDefinitionReference_To_v1alpha1_NetworkAttachmentDefinitionReference is an autogenerated conversion function.
func Convert_kubevirt_NetworkAttachmentDefinitionReference_To_v1alpha1_NetworkAttachmentDefinitionReference(in *kubevirt.NetworkAttachmentDefinitionReference, out *NetworkAttachmentDefinitionReference, s conversion.Scope) error {
	return autoConvert_kubevirt_NetworkAttachmentDefinitionReference_To_v1alpha1_NetworkAttachmentDefinitionReference(in, out, s)
}

func autoConvert_v1alpha1_NetworkStatus_To_kubevirt_NetworkStatus(in *NetworkStatus, out *kubevirt.NetworkStatus, s conversion.Scope) error {
	out.Name = in.Name
	out.Default = in.Default
	return nil
}

// Convert_v1alpha1_NetworkStatus_To_kubevirt_NetworkStatus is an autogenerated conversion function.
func Convert_v1alpha1_NetworkStatus_To_kubevirt_NetworkStatus(in *NetworkStatus, out *kubevirt.NetworkStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_NetworkStatus_To_kubevirt_NetworkStatus(in, out, s)
}

func autoConvert_kubevirt_NetworkStatus_To_v1alpha1_NetworkStatus(in *kubevirt.NetworkStatus, out *NetworkStatus, s conversion.Scope) error {
	out.Name = in.Name
	out.Default = in.Default
	return nil
}

// Convert_kubevirt_NetworkStatus_To_v1alpha1_NetworkStatus is an autogenerated conversion function.
func Convert_kubevirt_NetworkStatus_To_v1alpha1_NetworkStatus(in *kubevirt.NetworkStatus, out *NetworkStatus, s conversion.Scope) error {
	return autoConvert_kubevirt_NetworkStatus_To_v1alpha1_NetworkStatus(in, out, s)
}

func autoConvert_v1alpha1_NetworksConfig_To_kubevirt_NetworksConfig(in *NetworksConfig, out *kubevirt.NetworksConfig, s conversion.Scope) error {
	out.SharedNetworks = *(*[]kubevirt.NetworkAttachmentDefinitionReference)(unsafe.Pointer(&in.SharedNetworks))
	out.TenantNetworks = *(*[]kubevirt.TenantNetwork)(unsafe.Pointer(&in.TenantNetworks))
	return nil
}

// Convert_v1alpha1_NetworksConfig_To_kubevirt_NetworksConfig is an autogenerated conversion function.
func Convert_v1alpha1_NetworksConfig_To_kubevirt_NetworksConfig(in *NetworksConfig, out *kubevirt.NetworksConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_NetworksConfig_To_kubevirt_NetworksConfig(in, out, s)
}

func autoConvert_kubevirt_NetworksConfig_To_v1alpha1_NetworksConfig(in *kubevirt.NetworksConfig, out *NetworksConfig, s conversion.Scope) error {
	out.SharedNetworks = *(*[]NetworkAttachmentDefinitionReference)(unsafe.Pointer(&in.SharedNetworks))
	out.TenantNetworks = *(*[]TenantNetwork)(unsafe.Pointer(&in.TenantNetworks))
	return nil
}

// Convert_kubevirt_NetworksConfig_To_v1alpha1_NetworksConfig is an autogenerated conversion function.
func Convert_kubevirt_NetworksConfig_To_v1alpha1_NetworksConfig(in *kubevirt.NetworksConfig, out *NetworksConfig, s conversion.Scope) error {
	return autoConvert_kubevirt_NetworksConfig_To_v1alpha1_NetworksConfig(in, out, s)
}

func autoConvert_v1alpha1_TenantNetwork_To_kubevirt_TenantNetwork(in *TenantNetwork, out *kubevirt.TenantNetwork, s conversion.Scope) error {
	out.Name = in.Name
	out.Config = in.Config
	out.Default = in.Default
	return nil
}

// Convert_v1alpha1_TenantNetwork_To_kubevirt_TenantNetwork is an autogenerated conversion function.
func Convert_v1alpha1_TenantNetwork_To_kubevirt_TenantNetwork(in *TenantNetwork, out *kubevirt.TenantNetwork, s conversion.Scope) error {
	return autoConvert_v1alpha1_TenantNetwork_To_kubevirt_TenantNetwork(in, out, s)
}

func autoConvert_kubevirt_TenantNetwork_To_v1alpha1_TenantNetwork(in *kubevirt.TenantNetwork, out *TenantNetwork, s conversion.Scope) error {
	out.Name = in.Name
	out.Config = in.Config
	out.Default = in.Default
	return nil
}

// Convert_kubevirt_TenantNetwork_To_v1alpha1_TenantNetwork is an autogenerated conversion function.
func Convert_kubevirt_TenantNetwork_To_v1alpha1_TenantNetwork(in *kubevirt.TenantNetwork, out *TenantNetwork, s conversion.Scope) error {
	return autoConvert_kubevirt_TenantNetwork_To_v1alpha1_TenantNetwork(in, out, s)
}

func autoConvert_v1alpha1_WorkerConfig_To_kubevirt_WorkerConfig(in *WorkerConfig, out *kubevirt.WorkerConfig, s conversion.Scope) error {
	out.DNSPolicy = v1.DNSPolicy(in.DNSPolicy)
	out.DNSConfig = (*v1.PodDNSConfig)(unsafe.Pointer(in.DNSConfig))
	return nil
}

// Convert_v1alpha1_WorkerConfig_To_kubevirt_WorkerConfig is an autogenerated conversion function.
func Convert_v1alpha1_WorkerConfig_To_kubevirt_WorkerConfig(in *WorkerConfig, out *kubevirt.WorkerConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_WorkerConfig_To_kubevirt_WorkerConfig(in, out, s)
}

func autoConvert_kubevirt_WorkerConfig_To_v1alpha1_WorkerConfig(in *kubevirt.WorkerConfig, out *WorkerConfig, s conversion.Scope) error {
	out.DNSPolicy = v1.DNSPolicy(in.DNSPolicy)
	out.DNSConfig = (*v1.PodDNSConfig)(unsafe.Pointer(in.DNSConfig))
	return nil
}

// Convert_kubevirt_WorkerConfig_To_v1alpha1_WorkerConfig is an autogenerated conversion function.
func Convert_kubevirt_WorkerConfig_To_v1alpha1_WorkerConfig(in *kubevirt.WorkerConfig, out *WorkerConfig, s conversion.Scope) error {
	return autoConvert_kubevirt_WorkerConfig_To_v1alpha1_WorkerConfig(in, out, s)
}

func autoConvert_v1alpha1_WorkerStatus_To_kubevirt_WorkerStatus(in *WorkerStatus, out *kubevirt.WorkerStatus, s conversion.Scope) error {
	out.MachineImages = *(*[]kubevirt.MachineImage)(unsafe.Pointer(&in.MachineImages))
	return nil
}

// Convert_v1alpha1_WorkerStatus_To_kubevirt_WorkerStatus is an autogenerated conversion function.
func Convert_v1alpha1_WorkerStatus_To_kubevirt_WorkerStatus(in *WorkerStatus, out *kubevirt.WorkerStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_WorkerStatus_To_kubevirt_WorkerStatus(in, out, s)
}

func autoConvert_kubevirt_WorkerStatus_To_v1alpha1_WorkerStatus(in *kubevirt.WorkerStatus, out *WorkerStatus, s conversion.Scope) error {
	out.MachineImages = *(*[]MachineImage)(unsafe.Pointer(&in.MachineImages))
	return nil
}

// Convert_kubevirt_WorkerStatus_To_v1alpha1_WorkerStatus is an autogenerated conversion function.
func Convert_kubevirt_WorkerStatus_To_v1alpha1_WorkerStatus(in *kubevirt.WorkerStatus, out *WorkerStatus, s conversion.Scope) error {
	return autoConvert_kubevirt_WorkerStatus_To_v1alpha1_WorkerStatus(in, out, s)
}
